version: '3'
services:
  web:
    build: .
    container_name: DjangoTest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - pgdb2
    networks:
      - mynetwork
  pgdb2:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mynetwork
    container_name: pgdb2
networks:
  mynetwork: